### ISSUE TITLE
初步完成概念框架中的issue

### ISSUE THREAD

**Issue by johnzjq** [tiev-tongji/tiev-sim#3]
# Function of this feature

每一位参与者，根据所负责的任务补充issue。注意区分EPIC issue和 feature issue。另外，在issue中请标记Label。

## Tasks1 API

- [ ] 完成carla学习和ros-bridge学习issue
- [ ] 完成ros1.x和2.0学习issue
- [ ] 完成zcm学习issue
- [ ] 完成cyberRT学习issue
- [ ] 完成设计PlanningAgent消息设计issue
- [ ] 完成设计FullstackAgent消息设计issue
- [ ] 完成xx消息实现issue

## Unit Tests

- [x] 暂无

## Tasks2 High performance Carla server

- [ ] 完成融合异步仿真issue
- [ ] 完成激光雷达GPU仿真issue
- [ ] 完成多屏优化issue

## Unit Tests

- [ ] 暂无

## Tasks3 Distributed Carla server

- [ ] 完成现有分布式Carla server复现issue
- [ ] 完成现有系统瓶颈分析issue
- [ ] 完成现有系统优化设计issue
- [ ] 完成现有系统优化issue
- [ ] 完成现有系统测试issue
- [ ]  完成多GPU仿真issue

## Unit Tests

- [x] 暂无

## Tasks4 Benchmarker

- [ ] 完成全局Benchmark设计 issue
- [ ] 完成用例Benchmark设计 issue
- [ ] 完成Benchmark系统设计相关issue
- [ ] 完成Benchmark系统实现相关 issue

## Unit Tests

- [x] 暂无

## Tasks5 Test case

- [ ] 完成Test case openscenario设计 issue
- [ ] 完成Test case benchmark相关 issue
- [ ] 完成Test case 生成方法相关 issue

## Unit Tests

- [x] 暂无
